### ISSUE TITLE
GetRawConfig() empty in terraform-provider-azapi

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-terraform-bridge#1021]
### What happened?

Courtesy of @tmeckel 

Repo: https://github.com/dirien/pulumi-azapi
TF Provider: https://github.com/Azure/terraform-provider-azapi
Problematic Code: https://github.com/Azure/terraform-provider-azapi/blob/6775698b76a99b53be1afac398f9fa7f82fd834a/internal/services/azapi_resource.go#L162

Test code:

```
name: azapi-test
runtime: yaml
description: Pulumi program to test the Pulumi AzAPI provider

config:
  subscription-id:
    type: string

variables: {}

resources:
  resource-group:
    type: azapi:Resource
    properties:
      type: Microsoft.Resources/resourceGroups@2020-06-01
      parentId: "/subscriptions/${subscription-id}"
      name: rg-azapi-test
      body: |-
        {
          "location": "eastus2"
        }
      responseExportValues: [
          "*"
      ]

outputs: {}
```

Error :

```
error: Preview failed: diffing urn:pulumi:default::azapi-test::azapi:index/resource:Resource::resource-group: resource name can't be empty, either specifying a default name or a resource name
```

Relevant code:

```
onfig := d.GetRawConfig()
if !isConfigExist(config, "name") && len(meta.(*clients.Client).Features.DefaultNaming) == 0 {
    return fmt.Errorf("resource name can't be empty, either specifying a default name or a resource name")
}
...

func isConfigExist(config cty.Value, path string) bool {
	if config.CanIterateElements() {
		configMap := config.AsValueMap()
		if value, ok := configMap[path]; ok {
			if value.Type().IsListType() {
				return len(value.AsValueSlice()) != 0
			}
			return !value.IsNull()
		}
	}
	return false
}
```

If printing debug the result of config := d.GetRawConfig() , config is empty.

This behavior diverges from how the provider behaves under Terraform CLI.

### Expected Behavior

Behaves the same as under TF CLI.

### Steps to reproduce

See above.

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
