### ISSUE TITLE
Arrays representing TF sets are saved in state in the wrong order

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-terraform-bridge#2478]
Specifying this as an input:

```
[]string{"val2", "val3", "val1"}
```

in
```yaml
name: test
runtime: yaml
resources:
  mainRes:
  type: prov:index:Test
  properties:
    tests: %s
outputs:
  testOut: ${mainRes.tests}`
```

actually produces the following output:
```
[]string{"val1", "val2", "val3"}
```

This happens because the order of elements is lost during TF planning as TF sets are unordered.

This prevents the engine from displaying the diff correctly as it always uses indices to display the detailed diff.
