### ISSUE TITLE
PF Configure Cross-tests fail when a `null` is present in an array

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi-terraform-bridge#2555]
The following test fails:

```go
func TestConfigureNullInList(t *testing.T) {
	crosstests.Configure(t,
		schema.Schema{Attributes: map[string]schema.Attribute{
			"k": schema.ListAttribute{Optional: true, ElementType: types.StringType},
		}},
		map[string]cty.Value{
			"k": cty.ListVal([]cty.Value{
				cty.NullVal(cty.String),
				cty.StringVal("another-value"),
			}),
		},
	)
}
```

Generated HCL is:
```hcl
provider "test" {
  k = [null, "another-value"]
}
        
resource "test_res" "res" {}
```

Generated Pulumi YAML is:

```yaml
backend:
    url: file://./data
name: project
resources:
    p:
        properties:
            ks:
                - null
                - another-value
        type: pulumi:providers:test
runtime: yaml
```
