### ISSUE TITLE
Provider errors with `missing expected [` when MaxItemsOne is removed from a property when run under PRC

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-terraform-bridge#2914]
### What happened?

Under PRC we do not correctly handle TF/Pulumi  schema changes to a property's MaxItemsOne value.

Under non-PRC this will correctly work and produce a diff in the property which has changed its `MaxItemsOne`-ness

This a special case of https://github.com/pulumi/pulumi-terraform-bridge/issues/1667 which happens often in the wild and  we already have code to handle explicitly.

### Example

Changing
```golang
&schema.Resource{
	Schema: map[string]*schema.Schema{"prop": {
		Type:     schema.TypeList,
		Optional: true,
		Elem:     &schema.Schema{Type: schema.TypeString},
	}},
}
```

to

```golang
&schema.Resource{
	Schema: map[string]*schema.Schema{"prop": {
		Type:     schema.TypeList,
		Optional: true,
		MaxItems: 1,
		Elem:     &schema.Schema{Type: schema.TypeString},
	}},
}
```

and the following pulumi program:

```yaml
name: project
resources:
    example:
        properties:
            props:
                - a
```

changed to

```yaml
name: project
resources:
    example:
        properties:
            prop: a
```

I've also found at least fout instances of this reported in providers:

https://github.com/pulumi/pulumi-aws/issues/4015
https://github.com/pulumi/pulumi-aws/issues/4471
https://github.com/pulumi/pulumi-gcp/issues/2471
https://github.com/pulumi/pulumi-terraform-bridge/issues/1667#issuecomment-2568117472

Bridge repro in https://github.com/pulumi/pulumi-terraform-bridge/pull/2912

### Output of `pulumi about`

.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
