### ISSUE TITLE
Cannot derive an encoder for property "timeouts": expected a Map, got tftypes.Object

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-terraform-bridge#968]
### What happened?

This bug arose on an experimental build of pulumi-aws provider https://github.com/pulumi/pulumi-aws/pull/2453 that combines traditional and Plugin Framework based resources. One of the new PF based resources fails on `pulumi preview`

```
name: check
runtime: yaml
description: A minimal Pulumi YAML program
outputs: {}
resources:
  bucket1:
    type: aws:s3:Bucket
  rexpl1:
    type: aws:resourceexplorer/index:Index
    properties:
      type: LOCAL
  # cidrcol1:
  #   type: aws:route53/cidrCollection:CidrCollection
  #   properties:
  #    name: collection-1
variables: {}
```

```
pulumi preview                                                                                                                                                             ~/code/pulumi-aws/check
Previewing update (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/t0yv0/check/dev/previews/bf4d5ac3-606a-4ca2-8d9b-f5e78c8a79e6

     Type                           Name       Plan       Info
     pulumi:pulumi:Stack            check-dev             1 error
 +   └─ aws:resourceexplorer:Index  rexpl1     create     1 error


Diagnostics:
  pulumi:pulumi:Stack (check-dev):
    error: preview failed

  aws:resourceexplorer:Index (rexpl1):
    error: Preview failed: Failed to prepare a resource encoder: cannot derive an encoder for resource "aws:resourceexplorer/index:Index": Cannot derive an encoder for property "timeouts": expected a Map, got tftypes.Object["create":tftypes.String, "delete":tftypes.String, "update":tftypes.String]

```

### Expected Behavior

pulumi up succeeds

### Steps to reproduce

NA

### Output of `pulumi about`

NA

### Additional context

NA

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
